$a  &= $b; // [$a] = integerType()
$a  |= $b; // [$a] = integerType()
$a  ^= $b; // [$a] = integerType()
$a <<= $b; // [$a] = integerType()
$a >>= $b; // [$a] = integerType()
$a  %= $b; // [$a] = integerType()
