$a & $b // (bitwise And)
        // [$a & $b] = stringType() or integerType()
        // if (($a and $b) = stringType()) => [$a & $b] = stringType()
        // if (($a or $b) != stringType()) => [$a & $b] = integerType()
$a | $b // (bitwise Or)
        // [$a | $b] = stringType() or integerType()
        // if (($a and $b) = stringType()) => [$a | $b] = stringType()
        // if (($a or $b) != stringType()) => [$a | $b] = integerType()
$a ^ $b // (bitwise Xor)
        // [$a ^ $b] = stringType() or integerType()
        // if (($a and $b) = stringType()) => [$a ^ $b] = stringType()
        // if (($a or $b) != stringType()) => [$a ^ $b] = integerType()
