(array)$a  // <: array(\any())
(bool)$a   // boolean()
(float)$a  // float()
(int)$a    // integer()
(object)$a // object()
(string)$a // string(), when $a == object() the object needs to have __toString()
(unset)$a  // null()
