$a == $b  /* bool() */
$a === $b /* bool() */
$a != $b  /* bool() */
$a <> $b  /* bool() */
$a !== $b /* bool() */
$a < $b   /* bool() */
$a > $b   /* bool() */
$a <= $b  /* bool() */
$a >= $b  /* bool() */