$a == $b  /* boolean() */
$a === $b /* boolean() */
$a != $b  /* boolean() */
$a <> $b  /* boolean() */
$a !== $b /* boolean() */
$a < $b   /* boolean() */
$a > $b   /* boolean() */
$a <= $b  /* boolean() */
$a >= $b  /* boolean() */
