$a and $b // [$a and $b] = booleanType()
$a or $b  // [$a or $b]  = booleanType()
$a xor $b // [$a xor $b] = booleanType()
$a && $b  // [$a && $b]  = booleanType()
$a || $b  // [$a || $b]  = booleanType()
